### ISSUE TITLE
Re-arrange the React files well

### ISSUE THREAD

**Issue by Abdirizaks12** [Abdirizaks12/my-travel-journal-REACT-PROJECT#1]
re-arrange the files well so that the project runs

**Comment by Esha-in-arena** [comment]
@Abdirizaks12 hey i know how to do this.assign this to me.

**Comment by Abdirizaks12** [comment]
> @Abdirizaks12 hey i know how to do this.assign this to me.

there you go.

**Comment by Abdirizaks12** [comment]
just put the header ,journal, main and app files in a folder called components only.
